services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: rocketchat-gotify-gateway
    volumes:
      - .:/app
    restart: on-failure
    network_mode: host

  gotify:
    image: gotify/server
    container_name: rocketchat-gotify
    restart: unless-stopped
    ports:
      - "${GOTIFY_PORT}:80"
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_ADMIN_USERNAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_ADMIN_PASSWORD}
    volumes:
      - ./gotify_data:/app/data
    